### ISSUE TITLE
Does not compile with bullet 3.24

### ISSUE THREAD

**Issue by paolo-bolzoni** [danyalzia/irrBullet#5]
It seems bullet changed how gravity is implemented.

```
g++ -I /usr/include/irrlicht -I /usr/include -I /usr/include/bullet  -Iinclude -MM -MF src/irrBulletKinematicCharacterController.d src/irrBulletKinematicCharacterController.cpp
g++ -std=c++11 -Wall -pipe -fno-exceptions -fno-rtti -fstrict-aliasing -fexpensive-optimizations -O3 -I /usr/include/irrlicht -I /usr/include -I /usr/include/bullet  -Iinclude -I/usr/X11R6/include  -c -o src/irrBulletKinematicCharacterController.o src/irrBulletKinematicCharacterController.cpp
src/irrBulletKinematicCharacterController.cpp: In member function ‘void IKinematicCharacterController::setUpAxis(irr::u32)’:
src/irrBulletKinematicCharacterController.cpp:86:20: error: ‘class btKinematicCharacterController’ has no member named ‘setUpAxis’
   86 |         Character->setUpAxis(axis);
      |                    ^~~~~~~~~
src/irrBulletKinematicCharacterController.cpp: In member function ‘void IKinematicCharacterController::setGravity(irr::f32)’:
src/irrBulletKinematicCharacterController.cpp:101:31: error: cannot convert ‘irr::f32’ {aka ‘float’} to ‘const btVector3&’
  101 |         Character->setGravity(gravity);
      |                               ^~~~~~~
      |                               |
      |                               irr::f32 {aka float}
In file included from src/irrBulletKinematicCharacterController.cpp:9:
/usr/include/bullet/BulletDynamics/Character/btKinematicCharacterController.h:179:42: note:   initializing argument 1 of ‘void btKinematicCharacterController::setGravity(const btVector3&)’
  179 |         void setGravity(const btVector3& gravity);
      |                         ~~~~~~~~~~~~~~~~~^~~~~~~
src/irrBulletKinematicCharacterController.cpp: In member function ‘irr::f32 IKinematicCharacterController::getGravity() const’:
src/irrBulletKinematicCharacterController.cpp:138:37: error: cannot convert ‘btVector3’ to ‘irr::f32’ {aka ‘float’} in return
  138 |         return Character->getGravity();
      |                ~~~~~~~~~~~~~~~~~~~~~^~
      |                                     |
      |                                     btVector3
```
